sudo: required

services:
    - docker

before_install:
     ls
#    - docker pull tgrogers/gpgpu-sim_regress
#    - docker run tgrogers/gpgpu-sim_regress /bin/bash -c "pwd; ls"

language: cpp

script:
    ls && pwd && ls /
