sudo: required

services:
    - docker

before_install:
    - docker pull tgrogers/gpgpu-sim_regress:firsttry

language: cpp

script: docker run -v `pwd`:/home/runner/gpgpu-sim_distribution:rw tgrogers/gpgpu-sim_regress:firsttry /bin/bash -c "./start_torque.sh; chown -R runner /home/runner/gpgpu-sim_distribution; su - runner -c 'source /home/runner/gpgpu-sim_distribution/setup_environment && make -j -C /home/runner/gpgpu-sim_distribution && cd /home/runner/gpgpu-sim_simulations/ && git pull && /home/runner/gpgpu-sim_simulations/util/job_launching/run_simulations.py -N regress && while true; do lscpu; cat /var/spool/torque/server_logs/\`ls /var/spool/torque/server_logs\`; ps -aux | grep -i pbs; done'"
