sudo: required

services:
    - docker

before_install:
    - docker pull tgrogers/gpgpu-sim_regress:firsttry

language: cpp

script: docker run -v `pwd`:/home/runner/gpgpu-sim_distribution:rw tgrogers/gpgpu-sim_regress:firsttry /bin/bash -c "echo \"\\\$loglevel 7\" >> /var/spool/torque/mom_priv/config; while true; do /usr/sbin/pbs_mom ;ps -aux | grep -i pbs; sleep 5s ; ps -aux | grep -i pbs; cat /var/spool/torque/mom_logs/\`ls -tr /var/spool/torque/mom_logs | tail -1\`;done"
#script: docker run -v `pwd`:/home/runner/gpgpu-sim_distribution:rw tgrogers/gpgpu-sim_regress:firsttry /bin/bash -c "echo \"\\\$loglevel 7\" >> /var/spool/torque/mom_priv/config; ./start_torque.sh; ps -aux | grep -i pbs; cat /etc/hosts ;chown -R runner /home/runner/gpgpu-sim_distribution; echo \"mom_2\" && /etc/init.d/torque-mom restart && ps -aux | grep -i pbs && su - runner -c 'source /home/runner/gpgpu-sim_distribution/setup_environment && make -j -C /home/runner/gpgpu-sim_distribution && cd /home/runner/gpgpu-sim_simulations/ && git pull && /home/runner/gpgpu-sim_simulations/util/job_launching/run_simulations.py -N regress && while true; do lscpu; cat /var/spool/torque/server_logs/\`ls /var/spool/torque/server_logs\`; echo \"mom_logs\"; cat /var/spool/torque/mom_logs/\`ls /var/spool/torque/mom_logs\`; ps -aux | grep -i pbs; done'"
