sudo: required

services:
    - docker

before_install:
    - docker pull tgrogers/gpgpu-sim_regress:firsttry
    - docker run tgrogers/gpgpu-sim_regress /bin/bash -c "pwd; ls"

language: cpp

script:
    ls && pwd && ls /
